version: '3'
services:
  jenkins:
    build: .
    restart: always
    volumes:
      - ../Shared/jenkins_home:/var/jenkins_home
      - ../Shared/keys/keystore.jks:/var/lib/jenkins/keystore.jks
      - ../Shared/android_home:/opt/android/sdk
    environment:
      ANDROID_NDK_VERSION: 17.2.4988734
      ANDROID_CMAKE_VERSION: 3.10.2.4988404
      JAVA_OPTS: -Duser.timezone=CET
      JENKINS_OPTS: --httpPort=-1 --httpsPort=8083 --httpsKeyStore=/var/lib/jenkins/keystore.jks --httpsKeyStorePassword=keystore_pass
    ports:
      - 8083:8083
      - 50000:50000